// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_SNIP
NumericVector cpp_SNIP(NumericVector intensity, int iterations, bool decreasing, bool nonnegative);
RcppExport SEXP _MALDIassist_cpp_SNIP(SEXP intensitySEXP, SEXP iterationsSEXP, SEXP decreasingSEXP, SEXP nonnegativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    Rcpp::traits::input_parameter< bool >::type nonnegative(nonnegativeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_SNIP(intensity, iterations, decreasing, nonnegative));
    return rcpp_result_gen;
END_RCPP
}
// cpp_SNIP_spectrum
DataFrame cpp_SNIP_spectrum(NumericMatrix spectrum, int iterations, bool decreasing, bool nonnegative, bool corrected_nonnegative);
RcppExport SEXP _MALDIassist_cpp_SNIP_spectrum(SEXP spectrumSEXP, SEXP iterationsSEXP, SEXP decreasingSEXP, SEXP nonnegativeSEXP, SEXP corrected_nonnegativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type spectrum(spectrumSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    Rcpp::traits::input_parameter< bool >::type nonnegative(nonnegativeSEXP);
    Rcpp::traits::input_parameter< bool >::type corrected_nonnegative(corrected_nonnegativeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_SNIP_spectrum(spectrum, iterations, decreasing, nonnegative, corrected_nonnegative));
    return rcpp_result_gen;
END_RCPP
}
// cpp_TopHat
NumericVector cpp_TopHat(NumericVector intensity, int half_window, bool nonnegative);
RcppExport SEXP _MALDIassist_cpp_TopHat(SEXP intensitySEXP, SEXP half_windowSEXP, SEXP nonnegativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< int >::type half_window(half_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type nonnegative(nonnegativeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_TopHat(intensity, half_window, nonnegative));
    return rcpp_result_gen;
END_RCPP
}
// cpp_TopHat_spectrum
DataFrame cpp_TopHat_spectrum(NumericMatrix spectrum, int half_window, bool nonnegative, bool corrected_nonnegative);
RcppExport SEXP _MALDIassist_cpp_TopHat_spectrum(SEXP spectrumSEXP, SEXP half_windowSEXP, SEXP nonnegativeSEXP, SEXP corrected_nonnegativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type spectrum(spectrumSEXP);
    Rcpp::traits::input_parameter< int >::type half_window(half_windowSEXP);
    Rcpp::traits::input_parameter< bool >::type nonnegative(nonnegativeSEXP);
    Rcpp::traits::input_parameter< bool >::type corrected_nonnegative(corrected_nonnegativeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_TopHat_spectrum(spectrum, half_window, nonnegative, corrected_nonnegative));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_peak_prominence
NumericVector cpp_calculate_peak_prominence(NumericMatrix data, NumericMatrix peaks, std::string valley_type, double zero_tol);
RcppExport SEXP _MALDIassist_cpp_calculate_peak_prominence(SEXP dataSEXP, SEXP peaksSEXP, SEXP valley_typeSEXP, SEXP zero_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< std::string >::type valley_type(valley_typeSEXP);
    Rcpp::traits::input_parameter< double >::type zero_tol(zero_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_peak_prominence(data, peaks, valley_type, zero_tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_estimate_peak_strength
NumericVector cpp_estimate_peak_strength(SEXP data, SEXP peaks, double k, std::string normalization);
RcppExport SEXP _MALDIassist_cpp_estimate_peak_strength(SEXP dataSEXP, SEXP peaksSEXP, SEXP kSEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_estimate_peak_strength(data, peaks, k, normalization));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_peaks_fast
NumericMatrix cpp_find_peaks_fast(NumericMatrix data, double hws_peaks, int plateau);
RcppExport SEXP _MALDIassist_cpp_find_peaks_fast(SEXP dataSEXP, SEXP hws_peaksSEXP, SEXP plateauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type hws_peaks(hws_peaksSEXP);
    Rcpp::traits::input_parameter< int >::type plateau(plateauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_peaks_fast(data, hws_peaks, plateau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_savitzkyGolay_filter
NumericVector cpp_savitzkyGolay_filter(NumericVector y, int hws, int pno);
RcppExport SEXP _MALDIassist_cpp_savitzkyGolay_filter(SEXP ySEXP, SEXP hwsSEXP, SEXP pnoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type hws(hwsSEXP);
    Rcpp::traits::input_parameter< int >::type pno(pnoSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_savitzkyGolay_filter(y, hws, pno));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussKDE
NumericVector cpp_gaussKDE(NumericVector x, NumericVector x_obs, NumericVector y_obs, double bw);
RcppExport SEXP _MALDIassist_cpp_gaussKDE(SEXP xSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussKDE(x, x_obs, y_obs, bw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussKDE_1st_deriv
NumericVector cpp_gaussKDE_1st_deriv(NumericVector x, NumericVector x_obs, NumericVector y_obs, double bw);
RcppExport SEXP _MALDIassist_cpp_gaussKDE_1st_deriv(SEXP xSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussKDE_1st_deriv(x, x_obs, y_obs, bw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussKDE_2nd_deriv
NumericVector cpp_gaussKDE_2nd_deriv(NumericVector x, NumericVector x_obs, NumericVector y_obs, double bw);
RcppExport SEXP _MALDIassist_cpp_gaussKDE_2nd_deriv(SEXP xSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussKDE_2nd_deriv(x, x_obs, y_obs, bw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussKDE_3rd_deriv
NumericVector cpp_gaussKDE_3rd_deriv(NumericVector x, NumericVector x_obs, NumericVector y_obs, double bw);
RcppExport SEXP _MALDIassist_cpp_gaussKDE_3rd_deriv(SEXP xSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussKDE_3rd_deriv(x, x_obs, y_obs, bw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussKDE_all
NumericMatrix cpp_gaussKDE_all(NumericVector x, NumericVector x_obs, NumericVector y_obs, double bw);
RcppExport SEXP _MALDIassist_cpp_gaussKDE_all(SEXP xSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussKDE_all(x, x_obs, y_obs, bw));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bisection_root
double cpp_bisection_root(Function fun, double x_left, double x_right, double yi, double tol, int max_iter);
RcppExport SEXP _MALDIassist_cpp_bisection_root(SEXP funSEXP, SEXP x_leftSEXP, SEXP x_rightSEXP, SEXP yiSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< double >::type x_left(x_leftSEXP);
    Rcpp::traits::input_parameter< double >::type x_right(x_rightSEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bisection_root(fun, x_left, x_right, yi, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_roots
NumericVector cpp_find_roots(Function fun, NumericVector x, double yi, double tol, int max_iter);
RcppExport SEXP _MALDIassist_cpp_find_roots(SEXP funSEXP, SEXP xSEXP, SEXP yiSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type fun(funSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_roots(fun, x, yi, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_roots_on_grid
NumericVector cpp_find_roots_on_grid(NumericVector x, NumericVector y_grid, NumericVector x_obs, NumericVector y_obs, double bw, double yi, double tol, int max_iter);
RcppExport SEXP _MALDIassist_cpp_find_roots_on_grid(SEXP xSEXP, SEXP y_gridSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP, SEXP yiSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_grid(y_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< double >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_roots_on_grid(x, y_grid, x_obs, y_obs, bw, yi, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_extrema_from_grid
List cpp_find_extrema_from_grid(NumericVector x, NumericVector d1_grid, NumericVector x_obs, NumericVector y_obs, double bw, double tol, int max_iter);
RcppExport SEXP _MALDIassist_cpp_find_extrema_from_grid(SEXP xSEXP, SEXP d1_gridSEXP, SEXP x_obsSEXP, SEXP y_obsSEXP, SEXP bwSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d1_grid(d1_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_obs(x_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_obs(y_obsSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_extrema_from_grid(x, d1_grid, x_obs, y_obs, bw, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// cpp_curvature
NumericVector cpp_curvature(NumericVector x, Function first_deriv, Function second_deriv, bool absolute);
RcppExport SEXP _MALDIassist_cpp_curvature(SEXP xSEXP, SEXP first_derivSEXP, SEXP second_derivSEXP, SEXP absoluteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type first_deriv(first_derivSEXP);
    Rcpp::traits::input_parameter< Function >::type second_deriv(second_derivSEXP);
    Rcpp::traits::input_parameter< bool >::type absolute(absoluteSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_curvature(x, first_deriv, second_deriv, absolute));
    return rcpp_result_gen;
END_RCPP
}
// cpp_curvature_from_derivs
NumericVector cpp_curvature_from_derivs(NumericVector d1, NumericVector d2, bool absolute);
RcppExport SEXP _MALDIassist_cpp_curvature_from_derivs(SEXP d1SEXP, SEXP d2SEXP, SEXP absoluteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< bool >::type absolute(absoluteSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_curvature_from_derivs(d1, d2, absolute));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MALDIassist_cpp_SNIP", (DL_FUNC) &_MALDIassist_cpp_SNIP, 4},
    {"_MALDIassist_cpp_SNIP_spectrum", (DL_FUNC) &_MALDIassist_cpp_SNIP_spectrum, 5},
    {"_MALDIassist_cpp_TopHat", (DL_FUNC) &_MALDIassist_cpp_TopHat, 3},
    {"_MALDIassist_cpp_TopHat_spectrum", (DL_FUNC) &_MALDIassist_cpp_TopHat_spectrum, 4},
    {"_MALDIassist_cpp_calculate_peak_prominence", (DL_FUNC) &_MALDIassist_cpp_calculate_peak_prominence, 4},
    {"_MALDIassist_cpp_estimate_peak_strength", (DL_FUNC) &_MALDIassist_cpp_estimate_peak_strength, 4},
    {"_MALDIassist_cpp_find_peaks_fast", (DL_FUNC) &_MALDIassist_cpp_find_peaks_fast, 3},
    {"_MALDIassist_cpp_savitzkyGolay_filter", (DL_FUNC) &_MALDIassist_cpp_savitzkyGolay_filter, 3},
    {"_MALDIassist_cpp_gaussKDE", (DL_FUNC) &_MALDIassist_cpp_gaussKDE, 4},
    {"_MALDIassist_cpp_gaussKDE_1st_deriv", (DL_FUNC) &_MALDIassist_cpp_gaussKDE_1st_deriv, 4},
    {"_MALDIassist_cpp_gaussKDE_2nd_deriv", (DL_FUNC) &_MALDIassist_cpp_gaussKDE_2nd_deriv, 4},
    {"_MALDIassist_cpp_gaussKDE_3rd_deriv", (DL_FUNC) &_MALDIassist_cpp_gaussKDE_3rd_deriv, 4},
    {"_MALDIassist_cpp_gaussKDE_all", (DL_FUNC) &_MALDIassist_cpp_gaussKDE_all, 4},
    {"_MALDIassist_cpp_bisection_root", (DL_FUNC) &_MALDIassist_cpp_bisection_root, 6},
    {"_MALDIassist_cpp_find_roots", (DL_FUNC) &_MALDIassist_cpp_find_roots, 5},
    {"_MALDIassist_cpp_find_roots_on_grid", (DL_FUNC) &_MALDIassist_cpp_find_roots_on_grid, 8},
    {"_MALDIassist_cpp_find_extrema_from_grid", (DL_FUNC) &_MALDIassist_cpp_find_extrema_from_grid, 7},
    {"_MALDIassist_cpp_curvature", (DL_FUNC) &_MALDIassist_cpp_curvature, 4},
    {"_MALDIassist_cpp_curvature_from_derivs", (DL_FUNC) &_MALDIassist_cpp_curvature_from_derivs, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MALDIassist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
