# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_SNIP <- function(intensity, iterations = 50L, decreasing = TRUE, nonnegative = TRUE) {
    .Call(`_MALDIassist_cpp_SNIP`, intensity, iterations, decreasing, nonnegative)
}

cpp_SNIP_spectrum <- function(spectrum, iterations = 50L, decreasing = TRUE, nonnegative = TRUE, corrected_nonnegative = TRUE) {
    .Call(`_MALDIassist_cpp_SNIP_spectrum`, spectrum, iterations, decreasing, nonnegative, corrected_nonnegative)
}

cpp_TopHat <- function(intensity, half_window = 50L, nonnegative = TRUE) {
    .Call(`_MALDIassist_cpp_TopHat`, intensity, half_window, nonnegative)
}

cpp_TopHat_spectrum <- function(spectrum, half_window = 50L, nonnegative = TRUE, corrected_nonnegative = TRUE) {
    .Call(`_MALDIassist_cpp_TopHat_spectrum`, spectrum, half_window, nonnegative, corrected_nonnegative)
}

cpp_calculate_peak_prominence <- function(data, peaks, valley_type, zero_tol) {
    .Call(`_MALDIassist_cpp_calculate_peak_prominence`, data, peaks, valley_type, zero_tol)
}

cpp_estimate_peak_strength <- function(data, peaks, k = 1.0, normalization = "raw") {
    .Call(`_MALDIassist_cpp_estimate_peak_strength`, data, peaks, k, normalization)
}

cpp_find_peaks_fast <- function(data, hws_peaks = 10.0, plateau = 0L) {
    .Call(`_MALDIassist_cpp_find_peaks_fast`, data, hws_peaks, plateau)
}

cpp_savitzkyGolay_filter <- function(y, hws, pno) {
    .Call(`_MALDIassist_cpp_savitzkyGolay_filter`, y, hws, pno)
}

cpp_gaussKDE <- function(x, x_obs, y_obs, bw) {
    .Call(`_MALDIassist_cpp_gaussKDE`, x, x_obs, y_obs, bw)
}

cpp_gaussKDE_1st_deriv <- function(x, x_obs, y_obs, bw) {
    .Call(`_MALDIassist_cpp_gaussKDE_1st_deriv`, x, x_obs, y_obs, bw)
}

cpp_gaussKDE_2nd_deriv <- function(x, x_obs, y_obs, bw) {
    .Call(`_MALDIassist_cpp_gaussKDE_2nd_deriv`, x, x_obs, y_obs, bw)
}

cpp_gaussKDE_3rd_deriv <- function(x, x_obs, y_obs, bw) {
    .Call(`_MALDIassist_cpp_gaussKDE_3rd_deriv`, x, x_obs, y_obs, bw)
}

cpp_gaussKDE_all <- function(x, x_obs, y_obs, bw) {
    .Call(`_MALDIassist_cpp_gaussKDE_all`, x, x_obs, y_obs, bw)
}

cpp_bisection_root <- function(fun, x_left, x_right, yi, tol = 1e-5, max_iter = 100L) {
    .Call(`_MALDIassist_cpp_bisection_root`, fun, x_left, x_right, yi, tol, max_iter)
}

cpp_find_roots <- function(fun, x, yi, tol = 1e-5, max_iter = 100L) {
    .Call(`_MALDIassist_cpp_find_roots`, fun, x, yi, tol, max_iter)
}

cpp_find_roots_on_grid <- function(x, y_grid, x_obs, y_obs, bw, yi = 0.0, tol = 1e-5, max_iter = 100L) {
    .Call(`_MALDIassist_cpp_find_roots_on_grid`, x, y_grid, x_obs, y_obs, bw, yi, tol, max_iter)
}

cpp_find_extrema_from_grid <- function(x, d1_grid, x_obs, y_obs, bw, tol = 1e-5, max_iter = 100L) {
    .Call(`_MALDIassist_cpp_find_extrema_from_grid`, x, d1_grid, x_obs, y_obs, bw, tol, max_iter)
}

cpp_curvature <- function(x, first_deriv, second_deriv, absolute = TRUE) {
    .Call(`_MALDIassist_cpp_curvature`, x, first_deriv, second_deriv, absolute)
}

cpp_curvature_from_derivs <- function(d1, d2, absolute = TRUE) {
    .Call(`_MALDIassist_cpp_curvature_from_derivs`, d1, d2, absolute)
}

